name: Trevor Rice
markdown: redcarpet
highlighter: pygments # or rouge or null
exclude: ["node_modules", "gulpfile.js", "package.json", "README.md", "TODO.md"]
include: ['_pages']
environment: dev

page_gen:
  - data: 'projects'
    template: 'detail'
    name: 'href'
    dir: 'work'