name: Trevor Rice
authorname: Trevor Rice
description: Personal site of Trevor Rice, front-end web developer from Chicago, Illinois.
url: http://trevrice.com
markdown: redcarpet
highlighter: pygments # or rouge or null
exclude: ["node_modules", "gulpfile.js", "package.json", "assets/css/main.scss", "assets/css/main.css", "README.md", "TODO.md"]
include: ['_pages']

page_gen:
  - data: 'projects'
    template: 'detail'
    name: 'href'
    dir: 'work'